version: "3.9"
services:
  web:
    build: ./API
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Password123*"
      MSSQL_PID: Express
    expose: 
      - 1433
    volumes:
      - database_data:/var/opt/mssql

volumes:
  database_data: